Adding Instance Refresh Command
instructure-bridge/truss-cli pull request #49
Opened 2020-09-22 20:50 UTC by adamgoose

Closes https://getbridge.atlassian.net/browse/CC-621

2020-09-23 16:55 UTC, jgramoll commented on go.mod
> +	github.com/davecgh/go-spew v1.1.1
don't think we need this

2020-09-23 17:48 UTC, psi requested changes
As @jgramoll mentioned, I think go-spew needs to come out, but otherwise LGTM. The refactor on the filter functions is much clearer than the earlier version I looked at!

2020-09-23 17:53 UTC, adamgoose commented on cmd/refresh_nodes.go
> +				rnc.RefreshNodes(asg)
I also wanna handle errors here.

2020-09-23 22:10 UTC, jgramoll approved these changes

2020-09-24 04:13 UTC, psi approved these changes

2020-09-24 16:06 UTC, merged